fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:                               # this lines
        mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address: "skvor_vit@mail.ru"
        sender_name: "Vitaliy Skvortsov"
    resetting:
        token_ttl: 86400
