nelmio_api_doc:
    documentation:
        info:
            title: Skeleton
            description: Symfony-flex api skeleton
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api